version: '3'

#Build only (put your images in here)
services:
#An exmaple of how to add your code to databox
  driver-os-monitor:
    build:
        context: ./driver-os-monitor
        dockerfile: Dockerfile${DATABOX_ARCH}
    image: driver-os-monitor

  driver-twitter:
    build:
        context: ./driver-twitter
        dockerfile: Dockerfile${DATABOX_ARCH}
    image: driver-twitter

  app-twitter-sentiment:
    build:
        context: ./app-twitter-sentiment
        dockerfile: Dockerfile
    image: app-twitter-sentiment

#Build the datastores 
  store-json:
    build: 
        context: ./store-json
        dockerfile: Dockerfile${DATABOX_ARCH}
    image: store-json

