version: '2'
services:
  app-server:
    build:
        context: ./platform-app-server
        dockerfile: Dockerfile${DATABOX_ARCH}
    image: ${DOCKER_REPO}app-server
    environment:
        - "LOCAL_MODE=1"
        - "PORT=8181"
    ports:
        - '8181:8181'
